```{r}
library(here)
library(tidyverse)
library(rjtools)
library(learningtower)
library(ggplot2)
library(dplyr)
library(viridis)
library(patchwork)
library(plotly)
library(ggbeeswarm)
library(gganimate)
library(ggrepel)
```

```{r}
p1 <- ggplot(data = student_country,
             aes(x = math, y = read)) +
  geom_hex() +
  labs(x = "Math Scores",
       y = "Reading Scores") +
  theme(legend.position="none")

p2 <- ggplot(data = student_country,
             aes(x = math, y = science)) +
  geom_hex() +
  labs(x = "Math Scores",
       y = "Science Scores") +
  theme(legend.position = "none")

p3 <- ggplot(data = student_country,
             aes(x = read, y = science)) +
  geom_hex() +
  labs(x = "Reading Scores",
       y = "Science Scores") +
  theme(legend.position="none")
```

```{r corr-plot, fig.cap ="The scatterplot displays the relationship between math, reading, and science scores for all PISA countries that participated in the experiment in 2022. This scatterplot shows that all three subjects have a significant and positive correlation with one another.", fig.width=9, fig.pos = "H", out.width="100%", layout="l-body"}
p1+p2+p3
```

```{r}
father_qual_math_read_sci_data <- student_country %>%
  group_by(country_name, father_educ) %>%
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>%
  dplyr::mutate(father_educ = recode_factor(father_educ,
                "less than ISCED1" = "Early Childhood",
                "ISCED 1" = "Primary",
                "ISCED 2" = "Lower Secondary",
                "ISCED 3A" = "Upper Secondary",
                "ISCED 3B, C" = "Upper Secondary",
                .ordered = TRUE)) %>%
  na.omit() %>%
  rename(`Father's Education` = father_educ)

mother_qual_math_read_sci_data <- student_country %>%
  group_by(country_name, mother_educ) %>%
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>%
  dplyr::mutate(mother_educ = recode_factor(mother_educ,
                "less than ISCED1" = "Early Childhood",
                "ISCED 1" = "Primary",
                "ISCED 2" = "Lower Secondary",
                "ISCED 3A" = "Upper Secondary",
                "ISCED 3B, C" = "Upper Secondary",
                .ordered = TRUE)) %>%
  na.omit() %>%
  rename(`Mother's Education` = mother_educ)

mother_qual_math <- ggplot(mother_qual_math_read_sci_data,
       aes(x=`Mother's Education`,
           y=math_avg,
           col=`Mother's Education`)) +
  geom_quasirandom(size = 1.7,
             cex = 3) +
  geom_line(aes(group = country_name),
            size=0.5, alpha=.36) +
  scale_fill_viridis(discrete = TRUE,
                     option = "A",
                      alpha=0.2) +
    stat_summary(fun.y = median,
                 fun.ymin = median,
                 fun.ymax = median,
                 geom = "crossbar",
                 width = 0.5,
                 col = "black") +
  theme(legend.position="none",
      plot.title = element_text(size=11)) +
  labs(y = "Average Mathematics Score",
       x = "Mother's Qualification",
       title = "math Scores and Mother's Qualification")

father_qual_math <- ggplot(father_qual_math_read_sci_data,
       aes(x=`Father's Education`,
           y=math_avg,
           col=`Father's Education`)) +
  geom_quasirandom(size = 1.7,
             cex = 3) +
  geom_line(aes(group = country_name),
            size=0.5, alpha=.36) +
  scale_fill_viridis(discrete = TRUE,
                     option = "A",
                      alpha=0.2) +
    stat_summary(fun.y = median,
                 fun.ymin = median,
                 fun.ymax = median,
                 geom = "crossbar",
                 width = 0.5,
                 col = "black") +
  theme(legend.position="none",
      plot.title = element_text(size=11)) +
  labs(y = "Average Mathematics Score",
       x = "Father's Qualification",
       title = "math Scores and Father's Qualification")
```

```{r qual-plot, fig.cap ="The impact of parents' education on their children's academic progress is depicted in this graph. When the parents have greater levels of education, we see a considerable rise in scores and an increase in the median of scores for each category, as shown in the figure. In comparison to parents with lower levels of education qualifications. Parents who have tend to have upper secondary qualification or equivalent credentials their children are more likely to perform better in academics when compared with parent having lesser levels of qualifications.", fig.width= 15, fig.height= 8, fig.pos = "H", out.width="100%", layout="l-body"}
father_qual_math + mother_qual_math
```

```{r}
z_star_95 <- qnorm(0.975)

tv_math_data <- student_country %>%
  group_by(country_name, television) %>%
  dplyr::summarise(math_avg =
                     weighted.mean(math,
                                   w = stu_wgt,
                                   na.rm = TRUE),
                   lower = weighted.mean(math,
                      w = stu_wgt, na.rm = TRUE) -
                      z_star_95 * (sd(math, na.rm = TRUE)) /
                      sqrt(length(math)),
                   upper = weighted.mean(math,
                      w = stu_wgt, na.rm = TRUE) +
                      z_star_95 * (sd(math, na.rm = TRUE)) /
                     sqrt(length(math)),
                   .groups = "drop") %>%
  dplyr::mutate(television = recode_factor(television,
                "0" = "No TV",
                "1" = "1 TVs",
                "2" = "2 Tvs",
                "3+" = "3+ TVs",
               .ordered = TRUE)) %>%
  na.omit() %>%
  dplyr::select(country_name,
                television,
                math_avg,
                lower,
                upper)

linear_model <- function(y, x){
  coef(lm(y ~ x))[2]
}

tv_plot <- tv_math_data %>%
  group_by(country_name) %>%
  mutate(slope = linear_model(math_avg, television)) %>%
  ungroup() %>%
  mutate(country_name = fct_reorder(country_name, slope)) %>%
  ggplot(aes(x=as.numeric(television), y=math_avg)) +
  geom_ribbon(aes(ymin = lower, ymax = upper),
                colour="orange", fill = "orange",
              alpha=0.45) +
  geom_point(size=1.8) +
  geom_line() +
  facet_wrap(~country_name, ncol = 8, scales = "free") +
#  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
  theme(axis.text = element_blank()) +
  labs(x = "Number of TVs",
       y = "Average Mathematics Score")
```

```{r tv-plot, fig.cap ="Relationship  between number of TVs in a household and average math scores across countries. Number of TVs ranges from 0 to 3 or more. The orange bands indicate 95 percent standard confidence intervals. The impact of television on student performance is a contentious issue. It is interesting that in some countries for example in South Korea's effect appears to be positive, but in other countries like Poland and Germany there is a decline in average math scores.", fig.height=12, fig.width=12, fig.pos = "H", out.width="100%", layout="l-body"}
tv_plot
```

```{r}
z_star_95 <- qnorm(0.975)

book_math_read_sci_data <- student_country %>%
  group_by(country_name, book)  %>%
  dplyr::summarise(math_avg =
            weighted.mean(math,
              w = stu_wgt, na.rm = TRUE),
           bk_lower = weighted.mean(math,
              w = stu_wgt, na.rm = TRUE) -
              z_star_95 * (sd(math, na.rm = TRUE)) /
              sqrt(length(math)),
           bk_upper = weighted.mean(math,
              w = stu_wgt, na.rm = TRUE) +
              z_star_95 * (sd(math, na.rm = TRUE)) /
              sqrt(length(math)), .groups = "drop")  %>%
  dplyr::mutate(book = recode_factor(book,
                                     "0-10" = "1",
                                     "11-25" = "11",
                                     "26-100" = "26",
                                     "101-200" = "101",
                                     "201-500" = "201",
                                     "more than 500" = "500",
                                     .ordered = TRUE)) %>%
  na.omit()

linear_model <- function(y, x){
  coef(lm(y ~ x))[2]
}


book_plot <- book_math_read_sci_data %>%
  group_by(country_name) %>%
  mutate(slope = linear_model(math_avg, book)) %>%
  ungroup() %>%
  mutate(country_name = fct_reorder(country_name, slope)) %>%
  ggplot(aes(x=as.numeric(book), y=math_avg)) +
  geom_ribbon(aes(ymin = bk_lower, ymax = bk_upper),
                colour="orange", fill="orange", alpha=0.45) +
  geom_point(size=1.8) +
  geom_line(aes(group = country_name)) +
  facet_wrap(~country_name, ncol = 8, scales = "free") +
  theme(axis.text = element_blank()) +
  labs(x = "Number of Books",
       y = "Average Mathematics Score")
```

```{r book-plot, fig.cap ="Impact of the number of books on average math score. Number of books ranges from 0 to 500 and more. 95 percent standard confidence bands shown in orange. Math scores generally increase as the number of books increases. Averages for some countries at the higher number of books are less reliable, and hence the decline reflects more that there are few households with this many books than a true decline.", fig.height=12, fig.width=12, fig.pos = "H", out.width="100%", layout="l-body"}
book_plot
```

```{r}
int_math_read_sci_data <- student_country %>%
  group_by(country_name, internet) %>%
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>%
  na.omit()

comp_math_read_sci_data <- student_country %>%
  group_by(country_name, computer) %>%
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>%
  na.omit()


computer_plot <- comp_math_read_sci_data %>%
  ggplot(aes(x=computer,
             y= math_avg,
             group = country_name)) +
    geom_point(color = "black",
               size=0.36) +
    geom_line(size = .27,
              alpha = .45) +
    theme(legend.position = "none") +
    labs(x = "Possession of Computer",
         y = "Average Mathematics Score",
         title = "Impact of Computers on Average Math Scores")


internet_plot <- int_math_read_sci_data %>%
  ggplot(aes(x=internet,
             y= math_avg,
             group = country_name )) +
    geom_point(color = "black",
               size=0.36) +
    geom_line(size = .27,
              alpha = .45) +
    theme(legend.position = "none") +
    labs(x = "Access to Internet",
         y = "Average Mathematics Score",
         title = "Impact of Internet on Average Math Scores")
```

```{r compint-plot, fig.cap ="Computers and the Internet are two of the most important inventions in the history of technology. In this figure, we observe the impact of owning a computer and having access to the internet on 15-year-old students all over the world. A remarkable finding from the plot is that all nations have higher scores in student performance when they own a computer and have access to the internet.", fig.width=8, fig.height=4, fig.pos = "H", out.width="100%", layout="l-body"}
computer_plot + internet_plot
```

